services:
  ros2:
    build:
      dockerfile: docker/Dockerfile.ros2
      args:
        - USER_UID=${USER_UID}
        - USER_GID=${USER_GID}
    container_name: ${PROJECT_NAME}-ros2
    network_mode: host
    privileged: true
    tty: true
    stdin_open: true
    environment:
      - DISPLAY=${DISPLAY:-0}
      - XAUTHORITY=/tmp/.docker.xauth
      - ROS_DOMAIN_ID=${ROS_DOMAIN_ID:-0}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /tmp/.docker.xauth:/tmp/.docker.xauth
      - ${PROJECT_ROOT}/workspaces/ros2_ws:/ros2_ws
    working_dir: /ros2_ws
    restart: unless-stopped

  isaac_sim_hub:
    image: nvcr.io/nvidia/omniverse/hub_workstation_cache:2.0.0
    container_name: ${PROJECT_NAME}-isaac_sim_hub
    network_mode: "host"
    user: "1234:1234"
    volumes:
      - ${ISAACSIM_HUB_CACHE_PATH}:/var/cache/hub:rw
    restart: unless-stopped

  isaac_sim:
    build:
      dockerfile: docker/Dockerfile.isaac_sim
    container_name: ${PROJECT_NAME}-isaac_sim
    network_mode: "host"
    runtime: nvidia
    user: "1234:1234"
    stdin_open: true
    tty: true
    environment:
      - ROS_DOMAIN_ID=${ROS_DOMAIN_ID:-0}
      - NVIDIA_VISIBLE_DEVICES=${GPU_DEVICE:-all}
    volumes:
      - ${HOME}/.Xauthority:/isaac-sim/.Xauthority
      - ${ISAAC_SIM_DATA:-~/docker/isaac-sim}/cache/main:/isaac-sim/.cache:rw
      - ${ISAAC_SIM_DATA:-~/docker/isaac-sim}/cache/computecache:/isaac-sim/.nv/ComputeCache:rw
      - ${ISAAC_SIM_DATA:-~/docker/isaac-sim}/logs:/isaac-sim/.nvidia-omniverse/logs:rw
      - ${ISAAC_SIM_DATA:-~/docker/isaac-sim}/config:/isaac-sim/.nvidia-omniverse/config:rw
      - ${ISAAC_SIM_DATA:-~/docker/isaac-sim}/data:/isaac-sim/.local/share/ov/data:rw
      - ${ISAAC_SIM_DATA:-~/docker/isaac-sim}/pkg:/isaac-sim/.local/share/ov/pkg:rw
      - ${ISAACSIM_HUB_CACHE_PATH:-~/.cache/ov/hub}:/var/cache/hub:rw
      - ${PROJECT_ROOT}/workspaces/isaac_sim_ws:/isaac_sim/isaac_sim_ws
    depends_on:
      isaac_sim_hub:
        condition: service_started
    restart: unless-stopped
