# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - robot1_controller
    - robot2_controller

  robot1_controller:
    type: FollowJointTrajectory
    joints:
      - robot1_lt_J1
      - robot1_fanuc_J1
      - robot1_fanuc_J2
      - robot1_fanuc_J3
      - robot1_fanuc_J4
      - robot1_fanuc_J5
      - robot1_fanuc_J6
    action_ns: follow_joint_trajectory
    default: true
  robot2_controller:
    type: FollowJointTrajectory
    joints:
      - robot2_lt_J1
      - robot2_fanuc_J1
      - robot2_fanuc_J2
      - robot2_fanuc_J3
      - robot2_fanuc_J4
      - robot2_fanuc_J5
      - robot2_fanuc_J6
    action_ns: follow_joint_trajectory
    default: false